### ISSUE TITLE
Support for jsx syntax?

### ISSUE THREAD

**Issue by nightire** [jason0x43/vim-js-indent#4]
First of all, this is the best js indentation for vim I've ever used!

Only exception is for jsx syntax, this will break all the indentation in `javascript.jsx` files.

Below is my setting currently, FYI.

``` viml
Plug 'jason0x43/vim-js-indent', {'for': 'javascript'}
Plug 'pangloss/vim-javascript', {'for': ['javascript', 'javascript.jsx']}
Plug 'mxw/vim-jsx', {'for': 'javascript.jsx'} 
```

We're expecting the prefect suite for vim, thanks in advance.

**Comment by jason0x43** [comment]
Thanks!

I haven't dealt much with JSX, but I'll look into it.

**Comment by jason0x43** [comment]
I've tested a couple of JSX files, and I'm unable to reproduce this issue. With `vim-js-indent`, `vim-javascript`, and `vim-jsx` installed, JSX files are recognized as type `javascript.jsx` and both the JS and HTML contents appear to be indenting properly. Do you have a specific test case where you're seeing the issue?

**Comment by nightire** [comment]
@jason0x43 Thanks for your effort. I'm not sure whether other plugins will be effected, I have all my configuration on Github: https://github.com/nightire/dotfiles/blob/master/nvim%2Finit.vim#L308-L317

For now, I have to disabled `.jsx` detection. If I start vim and open a normal javascript file, then all indentation for jsx file will break, otherwise if open a jsx file first, then everything will be ok.

I'm so confused and have try lot of combination for a long long time, still no luck.

**Comment by nightire** [comment]
Interesting, I've just upgrade Neovim to newest version and cleanup some settings and then jsx support is come back~

Thanks any way.

But I've found a edge case that no javascript indent plugin can solve:

```javascript
  return async function webpackDevMiddleware(context, next) {
    const hasNext = await applyMiddleware(middleware, context.req, {
      send: content => context.body = content,
      ^^setHeader: function() {context.set.apply(context, arguments)}
    });
```

I add two `^` manually to indicate the problem, there shouldn't a indent, I have to un-indent this manually. Even I change this to a normal function expression (with curly braces) still got a wrong indentation.

Hope this will be fixed 😃

**Comment by jason0x43** [comment]
I pushed an update to the indenter (a rewrite, really) that handles the case mentioned above. Let me know if it breaks anything else for you. :)

**Comment by nightire** [comment]
@jason0x43 Awesome, I'll test it completely in recent days, thanks for your efforts, you are great!
